services:
  orderssystem:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ConnectionStrings__DefaultConnection=Host=db;Port=5432;Database=orders_db;Username=postgres;Password=postgres
    ports:
      - "5000:8080"
    depends_on:
      db:
        condition: service_healthy